language: node_js
node_js:
  - v6.14.3
  - v8.11.3
  - v10.5.0
deploy:
  - provider: script
    script: ./node_modules/.bin/nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: 10.5.0
services: memcached
